-- AlterTable
ALTER TABLE `orders` MODIFY `type` ENUM('DINE_IN', 'PICKUP', 'TAKEAWAY') NOT NULL,
    MODIFY `status` ENUM('PENDING', 'PREPARING', 'READY', 'SERVED', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';

